apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-empty-dir
  labels:
    app: nginx-empty-dir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-empty-dir
  template:
    metadata:
      labels:
        app: nginx-empty-dir
    spec:
      volumes:
        - name: nginx-volume
          emptyDir: {}
      containers:
      - name: nginx-container
        image: nginx
        ports:
          - containerPort: 80
            name: "http-server"
        volumeMounts:
          - mountPath:  /usr/share/nginx/html
            name: nginx-volume
