---
- name: Install required packages
  dnf:
    name:
      - curl
      - policycoreutils
      - openssh-server
      - perl
    state: latest

- name: Enable and start sshd
  service:
    name: sshd
    state: started
    enabled: yes

- name: Enable HTTP+HTTPS access
  firewalld:
    # This is how we use a variable
    service: "{{ item }}"
    permanent: yes
    state: enabled
  # The module will be run for each item
  with_items:
    - http
    - https

- name: Reload firewalld
  service:
    name: firewalld
    state: reloaded

- name: Install postfix
  dnf:
    name: postfix
    state: latest

- name: Enable and start postfix
  service:
    name: postfix
    state: started
    enabled: yes

- name: Download GitLab install script
  get_url:
    url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.rpm.sh
    dest: /tmp/script.rpm.sh

- name: Execute GitLab install script
  script: /tmp/script.rpm.sh

- name: Install GitLab
  dnf:
    name: gitlab-ee
  environment:
    EXTERNAL_URL: http://gitlab.local
